export default defineAppConfig({
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/index/index',
    'pages/meal-plan/index',
    'pages/blind-box/index',
    'pages/collection/index',
    'pages/settings/index',
    'pages/recipe/detail',
    'pages/recipe/form',
    'pages/cooking/index',
    'pages/shopping/index',
    'pages/login/index',
    'pages/data-manage/index',
  ],
  tabBar: {
    color: '#a8a08e',
    selectedColor: '#c9583a',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '寻味',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/meal-plan/index',
        text: '七日味',
        iconPath: 'assets/tab-plan.png',
        selectedIconPath: 'assets/tab-plan-active.png',
      },
      {
        pagePath: 'pages/blind-box/index',
        text: '味遇',
        iconPath: 'assets/tab-blind.png',
        selectedIconPath: 'assets/tab-blind-active.png',
      },
      {
        pagePath: 'pages/collection/index',
        text: '收藏',
        iconPath: 'assets/tab-heart.png',
        selectedIconPath: 'assets/tab-heart-active.png',
      },
      {
        pagePath: 'pages/settings/index',
        text: '小窝',
        iconPath: 'assets/tab-user.png',
        selectedIconPath: 'assets/tab-user-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#faf9f7',
    navigationBarTitleText: '知味',
    navigationBarTextStyle: 'black',
  },
})
