export default defineAppConfig({
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/home/index',
    'pages/calendar/index',
    'pages/meal-plan/index',
    'pages/fridge/index',
    'pages/settings/index',
    'pages/recipe/detail',
    'pages/recipe/form',
    'pages/cooking/index',
    'pages/collection/index',
    'pages/shopping/index',
    'pages/login/index',
    'pages/data-manage/index',
  ],
  tabBar: {
    color: '#a8a08e',
    selectedColor: '#c9583a',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '菜谱库',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/calendar/index',
        text: '日历',
        iconPath: 'assets/tab-calendar.png',
        selectedIconPath: 'assets/tab-calendar-active.png',
      },
      {
        pagePath: 'pages/meal-plan/index',
        text: '周计划',
        iconPath: 'assets/tab-plan.png',
        selectedIconPath: 'assets/tab-plan-active.png',
      },
      {
        pagePath: 'pages/fridge/index',
        text: '冰箱',
        iconPath: 'assets/tab-fridge.png',
        selectedIconPath: 'assets/tab-fridge-active.png',
      },
      {
        pagePath: 'pages/settings/index',
        text: '我的',
        iconPath: 'assets/tab-user.png',
        selectedIconPath: 'assets/tab-user-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#faf9f7',
    navigationBarTitleText: '菜谱助手',
    navigationBarTextStyle: 'black',
  },
})
